### ISSUE TITLE
enable cruise preview

### ISSUE THREAD

**Issue by GoogleCodeExporter** [SurfaceOceanCarbonAtlas/socat#46]
```
submits cruise to QC editor with special flag and soon after removes the cruise 
from the QC editor
```

Original issue reported on code.google.com by `karlmatt...@gmail.com` on 20 Apr 2014 at 6:06

**Comment by karlmattsmith** [comment]
Change of plans - preview now only shows plots of the one dataset in the dashboard and does not use the QC editor (LAS) at all.
